/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;

/**
 *
 * @author j
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
        initOtherComponents();
    }
    
    private void initOtherComponents() {
        file = new JFileChooser();
        file.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                if(f.isDirectory())
                    return true;
                String file = f.getPath();
                int indexDot = file.indexOf(".");
             //   if(indexDot == -1)
             //       indexDot = 0;
                String ext = file.substring(indexDot+1);
                return (("jpg".equals(ext)) || ("jpeg".equals(ext)) || ("png".equals(ext)) || ("bmp".equals(ext)));
            }

            @Override
            public String getDescription() {
                return "File picture (jpg|jpeg|png|bmp)";
            }
        });
        this.setLocationRelativeTo(this);
      //  pnlRoot.add(imgRoot);
      //  pnlResult.add(imgResult);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new ImagePanel();
        pnlResult = new ImagePanel();
        btnBrowserFile = new javax.swing.JButton();
        txtFile = new javax.swing.JTextField();
        btnChuanHoaXam = new javax.swing.JButton();
        btnTangCuongAnh = new javax.swing.JButton();
        btnNhiPhanHoa = new javax.swing.JButton();
        btnTaoXuong = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhận dạng vân tay");
        setResizable(false);

        pnlRoot.setBackground(new java.awt.Color(204, 204, 204));
        pnlRoot.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlRootLayout = new javax.swing.GroupLayout(pnlRoot);
        pnlRoot.setLayout(pnlRootLayout);
        pnlRootLayout.setHorizontalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        pnlRootLayout.setVerticalGroup(
            pnlRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        pnlResult.setBackground(new java.awt.Color(204, 204, 204));
        pnlResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pnlResultLayout = new javax.swing.GroupLayout(pnlResult);
        pnlResult.setLayout(pnlResultLayout);
        pnlResultLayout.setHorizontalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        pnlResultLayout.setVerticalGroup(
            pnlResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        btnBrowserFile.setText("Duyệt file");
        btnBrowserFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowserFileActionPerformed(evt);
            }
        });

        btnChuanHoaXam.setText("Chuẩn hóa mức xám");

        btnTangCuongAnh.setText("Tăng cường ảnh");

        btnNhiPhanHoa.setText("Nhị phân hóa ảnh");

        btnTaoXuong.setText("Tạo xương cơ bản");

        btnLuu.setText("Xem chi tiết");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFile, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowserFile))
                    .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChuanHoaXam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(btnTangCuongAnh)
                        .addGap(31, 31, 31)
                        .addComponent(btnNhiPhanHoa)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTaoXuong)
                        .addGap(18, 18, 18)
                        .addComponent(btnLuu)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowserFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChuanHoaXam)
                    .addComponent(btnTangCuongAnh)
                    .addComponent(btnNhiPhanHoa)
                    .addComponent(btnTaoXuong)
                    .addComponent(btnLuu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowserFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowserFileActionPerformed
        // TODO add your handling code here:
        if(file.showOpenDialog(this) == JFileChooser.OPEN_DIALOG) {
            txtFile.setText(file.getSelectedFile().toString());
            try {
                imgRoot = ImageIO.read(file.getSelectedFile());
                pnlRoot.updateImage(imgRoot);
            } catch (IOException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBrowserFileActionPerformed

    public BufferedImage getImage() {
        try {
                imgRoot = ImageIO.read(file.getSelectedFile());
            } catch (IOException ex) {
                Logger.getLogger(FormMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        return imgRoot;
    }
    
    public void yeuCauChuanHoaMucXam(ActionListener ac) {
        btnChuanHoaXam.addActionListener(ac);
    }
    
    public void yeuCauTangCuongChatLuongAnh(ActionListener ac) {
        btnTangCuongAnh.addActionListener(ac);
    }
    
    public void yeuCauTaoXuong(ActionListener ac) {
        btnTaoXuong.addActionListener(ac);
    }
    
    public void yeuCauNhiPhanHoaAnh(ActionListener ac) {
        btnNhiPhanHoa.addActionListener(ac);
    }
    
    public void yeuCauLuuDuLieu(ActionListener ac) {
        btnLuu.addActionListener(ac);
    }
    
    public void xemKetQua(BufferedImage img) {
        pnlResult.updateImage(img);
        // pnlResult.updateImage(img);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowserFile;
    private javax.swing.JButton btnChuanHoaXam;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhiPhanHoa;
    private javax.swing.JButton btnTangCuongAnh;
    private javax.swing.JButton btnTaoXuong;
    /*
    private javax.swing.JPanel pnlResult;
    */
    private ImagePanel pnlResult;
    /*
    private javax.swing.JPanel pnlRoot;
    */
    private ImagePanel pnlRoot;
    private javax.swing.JTextField txtFile;
    // End of variables declaration//GEN-END:variables
    private BufferedImage imgRoot;
    private JFileChooser file;
}
